backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
# local_backend: true

# publish_mode: editorial_workflow
media_folder: static/img # Media files will be stored in the repo under static/img
public_folder: /img

collections:
  - name: "product"
    label: "Product"
    folder: "content/product"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Order (used for sorting)", name: "order", widget: "number" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - { label: "Price (brutto)", name: "price-brutto", widget: "number" }
      - { label: "Short Description", name: "description-short", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
